### ISSUE TITLE
Upgrade to CNI v0.5.1

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#105]
Many CNI Plugins don't properly support DEL (See https://github.com/kubernetes/kubernetes/issues/43488 for more details).

We should upgrade to CNI v0.5.1 after https://github.com/kubernetes/kubernetes/pull/43546 is merged.

**Comment by feiskyer** [comment]
There are no actions should be taken in frakti actually. But we should document the requirements of cni plugin versions (at least v0.5.1).

**Comment by ethernetdan** [comment]
My understanding is that v0.5.1 is compatible with the currently vendored CNI code. I'm hesitant to make this change this close to releasing 1.6. I think this is a good candidate for 1.7.

**Comment by feiskyer** [comment]
Will be included in v0.1 release notes.
