### ISSUE TITLE
Enable full exec command failed tests

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#120]
The test is disabled at [#119](https://github.com/kubernetes/frakti/pull/119/files#diff-a1420ece84f1e6c17e782f06c394ad94R71) because of https://github.com/hyperhq/hyperd/issues/604. 

We should enable it again after https://github.com/hyperhq/hyperd/issues/604 is fixed.

**Comment by gnawux** [comment]
hyperhq/hyperd#604 has been fixed, could you verify if this issue is fixed as well?

**Comment by resouer** [comment]
@Crazykev Cloud please check if frakti exec e2e can work now?

**Comment by Crazykev** [comment]
@resouer Sure, will open a PR to test this.

**Comment by Crazykev** [comment]
Ops, seems not fixed yet, pls see logs in #121
I think this may not related with hyperhq/hyperd#604, since frakti cancel the request first.
```
Receive from stream error: rpc error: code = Canceled desc = context canceled
```

**Comment by Crazykev** [comment]
https://github.com/hyperhq/hyperd/pull/614 should fix this, let's try it later.

**Comment by feiskyer** [comment]
Enabled again via #121 .
