### ISSUE TITLE
Support port mapping

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#122]
CNI doesn't do port-mapping today. We could support port mapping via iptables.

**Comment by heartlock** [comment]
we can  use portmapping-manager  to do port mapping via iptables like https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/kubenet/kubenet_linux.go. What do you think? @feiskyer

**Comment by feiskyer** [comment]
@heartlock A standard CNI plugin is more preferred, e.g. https://github.com/containernetworking/plugins/pull/1, which is also depending on https://github.com/kubernetes/kubernetes/pull/42202.

**Comment by heartlock** [comment]
Cool! I will follow containernetworking/plugins#1

**Comment by heartlock** [comment]
Good news! containernetworking/plugins#1 was merged. I will start to work on supporting port mapping.

**Comment by feiskyer** [comment]
@heartlock We need to support cni plugin chaining first. Would you like to file a PR for this first?

Refer https://github.com/kubernetes/kubernetes/pull/42202.

**Comment by heartlock** [comment]
@feiskyer  Sure, will do it.
