### ISSUE TITLE
kubectl attach broken

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#123]
Test ENV:
kubernetes 1.6 + frakti + hyperd

Issue:
`kubectl attach` does not return anything

Expected:
`kubectl attach` should return process output in the container

**Comment by ravisantoshgudimetla** [comment]
@feiskyer Can you add some more information to this. I am interested in working on frakti and new to this code base. So, this will be a good starting point for me.

**Comment by Crazykev** [comment]
@feiskyer I haven't met any issue with attach when try with latest k8s+frakti+hyperd+hyperstart, while there is some issue when attach(along with container) exit and restart the container. This is a known issue related with https://github.com/hyperhq/hyperd/pull/585 and https://github.com/hyperhq/hyperstart/issues/294

**Comment by resouer** [comment]
@ravisantoshgudimetla  I updated the description, but it seems been fixed according to crazykev's comment. And a tech detail video about frakti is [here]( https://www.youtube.com/watch?v=phN1Ru0aDa4&list=PLj6h78yzYM2PAavlbv0iZkod4IVh_iGqV&index=51).

**Comment by feiskyer** [comment]
@Crazykev @resouer Yep, confirmed it has been fixed.

@ravisantoshgudimetla Thanks for the interest. The problems has been fixed in the upstream hyperd. Could you consider to contribute other parts, e.g. issues listed at https://github.com/kubernetes/frakti/issues.
