### ISSUE TITLE
No route to host/connection refused

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/frakti#136]
Performed a fresh install as before, clean Centos 7.3 VM , 1 master, 2 nodes

Everything looked good. Launched heapster, influxdb, grafana, dashboard

ran kubectl proxy as usual , default 127.0.0.1:8001

Accessing the dashboard:
http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/
yields - Error: 'dial tcp 10.244.1.3:9090: getsockopt: no route to host' Trying to reach: 'http://10.244.1.3:9090/'

Accessing grafana:
http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
yields - http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/

I will leave this cluster up for troubleshooting for the time being

DB

**Comment by feiskyer** [comment]
@DarkBlaez How the dashboard is deployed, It works ok in my settings:

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
```

Wait a while for pod up and then visit http://hostip:service-nodePort.

**Comment by DarkBlaez** [comment]
My question in reply is, are you starting from scratch,  clean Centos 7.3, and following the deploy or allinone.sh, then adding a second node? Each time I try this and the reason I've found the issues is from doing a clean install. I do this as common practice. Otherwise if I develop code and check it in, there is no guarantee a fresh install will work since I can't account for prior dependencies being met do to past installs.

**Comment by feiskyer** [comment]
Hmm, right. We are only support bridge plugin today, so it is expected for users to configure subnet routes on each host. I will add the guide later.

Could you add subnet routes on each host and try again?

**Comment by DarkBlaez** [comment]
I would need install guide to step me through adding subnet route to each host. Have not done it prior

**Comment by feiskyer** [comment]
@DarkBlaez Filed PR #137 for setting subnet routes, could you have a try on it?

**Comment by DarkBlaez** [comment]
I will start with fresh VMs and let you know results. By the way in the routes where are 10.140.0.2 and 10.140.0.3 coming from?

**Comment by feiskyer** [comment]
Hmm, sorry for the mistake. They are IPs of each host. Made a fix in the PR.

**Comment by DarkBlaez** [comment]
Just for continuity in documentation, deploy.md will need the updated steps which were included in the allinone.sh

Centos
-baseurl=http://yum.kubernetes.io/repos/kubernetes-el7-x86_64-unstable
+baseurl=http://yum.kubernetes.io/repos/kubernetes-el7-x86_64

And the appropriate changes for Ubuntu just to maintain continuity in documentation

Also I assume that the CNI entries for master and each subsequent node should be different?

So on master:
    "ipam": {
        "type": "host-local",
        "subnet": "10.244.1.0/24",
        "routes": [
            { "dst": "0.0.0.0/0"  }

Then node 1:
    "ipam": {
        "type": "host-local",
        "subnet": "10.244.2.0/24",
        "routes": [
            { "dst": "0.0.0.0/0"  }
 and so forth for each additional node, would this be a correct assumption?

Thanks
DB

**Comment by feiskyer** [comment]
@DarkBlaez Thanks. Would you like to file a PR for this?

**Comment by DarkBlaez** [comment]
Within the allinone.sh script I have noticed that when it runs for some reason the "setenforce 0" does not actually disable selinux. This may be do to the way the script runs. If I do each step manually then this gets set properly. I am going to step through this again doing it manually and accounting for the changes which were applied to the allinone.sh script which differs from deploy.md. I recreate fresh VMs and let you know the result

DB

**Comment by DarkBlaez** [comment]
Another item to note, this change is in the deploy.md but not in the allinone.sh. Is this needed for Centos 7?

deploy.md:
sed -i 's/native.cgroupdriver=systemd/native.cgroupdriver=cgroupfs/g' /usr/lib/systemd/system/docker.service

allinone.sh:
<not in the script>

DB

**Comment by DarkBlaez** [comment]
Whether I install manually or through the allinone.sh the result is the same. Likewise, the ip routes are simplistic and would work great on a set of VMs sitting on the same subnet. A situation which is ideal at best. I will put this on hold and come back to the project once things are further along. I think once this supports plugable networks like Calico, Flannel , etc I think things will go smoother
