### ISSUE TITLE
[Question] Calico or Flannel

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/frakti#150]
I'm thinking about spinning this back up across physical machines, about 5 HP Proliants to test. Where are things with supporting Calico or Flannel CNI?

Thanks
DB

**Comment by feiskyer** [comment]
@DarkBlaez Frakti does support calico and flannel currently, we are hoping to support them in next one or two releases.

**Comment by DarkBlaez** [comment]
Did you mean currently frakti does not support Calico or Flannel but that you hope to support them in the next one or two releases?

**Comment by feiskyer** [comment]
yep

**Comment by DarkBlaez** [comment]
Great, thanks so much

**Comment by resouer** [comment]
@YaoZengzeng claimed to fix both flannel and calico, assinged

**Comment by bruceherve** [comment]
I am a little confused I thought that any CNI  compliant network plugin would work out of the box. as request goes I would love to see support for cilium:  https://github.com/cilium/cilium. their approach to solve container security by using BGP is something interesting in this space. perhaps you could take a look and see if it is worth supporting it.

**Comment by YaoZengzeng** [comment]
Actually, flannel has already been supported.

**Comment by feiskyer** [comment]
Update: flannel master is supported now, hoping to support it in its next release.

**Comment by feiskyer** [comment]
Added in #196.
