### ISSUE TITLE
[Version] Clone master branch, frakti version?

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/frakti#163]
Does the version need updating in the code. I cloned the master branch, compiled, and result of frakti --version is:

I0605 11:24:34.272388   11749 frakti.go:71] frakti version: 0.1

Should this be 0.2? just wondering as I want to make sure I have the latest code with the ability to specify cpu and mem.

Thanks
DB

**Comment by feiskyer** [comment]
@DarkBlaez Good catch. Version should be updated indeed.
