### ISSUE TITLE
Compiled from git repo, restart nodes, kubelet fails

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/frakti#164]
1. Compiled current code base for frakti to pick up changes for default cpu/mem
2. Copied frakti binary to 1 master, 5 minon nodes
3. Restart all nodes

Result:
**KUBELET**
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Mon 2017-06-05 12:52:23 CDT; 1s ago
     Docs: http://kubernetes.io/docs/
  Process: 7419 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CGROUP_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
 Main PID: 7419 (code=exited, status=1/FAILURE)

Jun 05 12:52:23 master01 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Jun 05 12:52:23 master01 systemd[1]: Unit kubelet.service entered failed state.
Jun 05 12:52:23 master01 systemd[1]: kubelet.service failed.

**HYPERD**
● hyperd.service - hyperd
   Loaded: loaded (/usr/lib/systemd/system/hyperd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-05 12:50:52 CDT; 4min 46s ago
     Docs: http://docs.hypercontainer.io
 Main PID: 7193 (hyperd)
   CGroup: /system.slice/hyperd.service
           └─7193 /usr/bin/hyperd --log_dir=/var/log/hyper

Jun 05 12:50:52 master01 systemd[1]: Started hyperd.
Jun 05 12:50:52 master01 systemd[1]: Starting hyperd...
Jun 05 12:50:53 master01 hyperd[7193]: time="2017-06-05T12:50:53-05:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jun 05 12:50:53 master01 hyperd[7193]: time="2017-06-05T12:50:53-05:00" level=info msg="Firewalld running: false"
Jun 05 12:50:53 master01 hyperd[7193]: time="2017-06-05T12:50:53-05:00" level=info msg="Loading containers: start."
Jun 05 12:50:53 master01 hyperd[7193]: ...
Jun 05 12:50:53 master01 hyperd[7193]: time="2017-06-05T12:50:53-05:00" level=info msg="Loading containers: done."
Jun 05 12:50:53 master01 hyperd[7193]: E0605 12:50:53.215808    7193 persist.go:113] Pod[k8s_POD.0_kube-dns-2612786695-kqqhv_kube-system_4664f72a-409d-11e7-9579-0021ccd48ab5_9acb0442] failed to load sandbox info: leveldb: not found

**FRAKTI**
● frakti.service - Hypervisor-based container runtime for Kubernetes
   Loaded: loaded (/usr/lib/systemd/system/frakti.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-05 12:50:31 CDT; 5min ago
     Docs: https://github.com/kubernetes/frakti
 Main PID: 7126 (frakti)
   CGroup: /system.slice/frakti.service
           └─7126 /usr/bin/frakti --v=3 --log-dir=/var/log/frakti --logtostderr=false --cgroup-driver=systemd --listen=/var/run/frakti.sock --streaming-server-addr=master01 --hyper-endpoint=127.0.0.1:22318

Jun 05 12:50:31 master01 systemd[1]: Started Hypervisor-based container runtime for Kubernetes.
Jun 05 12:50:31 master01 systemd[1]: Starting Hypervisor-based container runtime for Kubernetes...
Jun 05 12:50:52 master01 frakti[7126]: 2017/06/05 12:50:52 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Jun 05 12:50:52 master01 frakti[7126]: 2017/06/05 12:50:52 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:22318: getsockopt: connection refused"; Reconnecting to {127.0.0.1:22318 <nil>}
Jun 05 12:52:22 master01 frakti[7126]: 2017/06/05 12:52:22 transport: http2Server.HandleStreams failed to read frame: read unix /var/run/frakti.sock->@: read: connection reset by peer
Jun 05 12:55:24 master01 frakti[7126]: 2017/06/05 12:55:24 transport: http2Server.HandleStreams failed to read frame: read unix /var/run/frakti.sock->@: read: connection reset by peer
Jun 05 12:55:45 master01 frakti[7126]: 2017/06/05 12:55:45 transport: http2Server.HandleStreams failed to read frame: read unix /var/run/frakti.sock->@: read: connection reset by peer

Another thing I've noticed is that that does not survive reboots all that well.

Thoughts where I should look?
DB

**Comment by feiskyer** [comment]
There is huge CRI change in kubernetes v1.7, which causes some incompatible problem (see https://github.com/kubernetes/kubernetes/issues/47012). 

Currently, frakti master works with kubernetes master, and frakti kubernetes-v1.6 branch works with kuberentes v1.6.x. 

@DarkBlaez could you have a try on frakti kubernetes-v1.6 branch? we have already cherry-picked bug fixes to it.

**Comment by DarkBlaez** [comment]
I had noticed that the init pulled in 1.7.0 so reset it with v1.6.4 and still had the same results. At this point the cluster is dead and wont become stable. So I will have to rebuild from OS again to get a clean cluster. This time around I will just stick with 1 master, 1 Minon to simplify troubleshooting and the impact of rebuilds. I choose baremetal over VM to avoid incurring 12% performance hits.

I will check out the various branches and redo this and see where things land. Thanks for the heads up.

DB

**Comment by DarkBlaez** [comment]
I recompiled from the kubernetest 1.6 branch and reapplied all changes to each node and created a new cluster. Everything is operational again and going to move on to bringing rook.io up given the new changes and see what the result is.

Thanks
DB

**Comment by feiskyer** [comment]
@DarkBlaez Cool 👍
