### ISSUE TITLE
Hyperd - POD  failed to load sandbox info: leveldb: not found

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/frakti#165]
For some reason hyperd is trying to initialize or load a POD.

1. kubeadm reset
2. systemctl restart hyperd

Result:
**HYPERD**
● hyperd.service - hyperd
   Loaded: loaded (/usr/lib/systemd/system/hyperd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-05 13:43:34 CDT; 27s ago
     Docs: http://docs.hypercontainer.io
 Main PID: 12880 (hyperd)
   CGroup: /system.slice/hyperd.service
           └─12880 /usr/bin/hyperd --log_dir=/var/log/hyper

Jun 05 13:43:34 master01 systemd[1]: Started hyperd.
Jun 05 13:43:34 master01 systemd[1]: Starting hyperd...
Jun 05 13:43:34 master01 hyperd[12880]: time="2017-06-05T13:43:34-05:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jun 05 13:43:34 master01 hyperd[12880]: time="2017-06-05T13:43:34-05:00" level=info msg="Firewalld running: false"
Jun 05 13:43:34 master01 hyperd[12880]: time="2017-06-05T13:43:34-05:00" level=info msg="Loading containers: start."
Jun 05 13:43:34 master01 hyperd[12880]: ...
Jun 05 13:43:34 master01 hyperd[12880]: time="2017-06-05T13:43:34-05:00" level=info msg="Loading containers: done."
Jun 05 13:43:34 master01 hyperd[12880]: E0605 13:43:34.835819   12880 persist.go:113] Pod[k8s_POD.0_kube-dns-2612786695-kqqhv_kube-system_4664f72a-409d-11e7-9579-0021ccd48ab5_9acb0442] failed to load sandbox info: leveldb: not found

**Comment by feiskyer** [comment]
@DarkBlaez Which version of hyperd are you using? I didn't reproduce the problem with latest hyperd.

**Comment by feiskyer** [comment]
The issue should be already fixed, closing it.
