### ISSUE TITLE
install kubernetes use this guide

### ISSUE THREAD

**Issue by yiqinguo** [kubernetes/frakti#166]
Hello:
I use this guide install kubernetes cluster,when start apiserver have a error like this:
unable to sync kubernetes service: Endpoints "kubernetes" is invalid: subsets[0].addresses[0].ip: Invalid value: "127.0.0.1": may not be in the loopback range (127.0.0.0/8)

what does that mean?

**Comment by resouer** [comment]
Do you mean you are using https://github.com/kubernetes/frakti/blob/master/docs/deploy.md ?

`unable to sync kubernetes service: Endpoints` means kubelet is loading an illegal kube-apiserver manifest, which is expected to be generated by kubeadm.

So could you please provide: 
1. the content in` /etc/kubernetes/manifests/kube-apiserver.yaml` 
2. the k8s version and kubeadm version

**Comment by feiskyer** [comment]
@yiqinguo Closing this issue since it is not related with frakti. The original question is at https://github.com/feiskyer/kubernetes-handbook/issues/27.
