### ISSUE TITLE
Not able to join worker nodes with kubeadm join

### ISSUE THREAD

**Issue by harshapic** [kubernetes/frakti#171]
Hi,

Followed steps as given in Readme everything is fine upto setting up master node.
But when i try to join worker node with kubeadm it is stuck as below:

kubeadm join --token bxxxxxxx  ip:6443[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Running pre-flight checks
[discovery] Trying to connect to API Server "192.168.63.161:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://192.168.63.161:6443"
[discovery] Cluster info signature and contents are valid, will use API Server "https://192.168.63.161:6443"
[discovery] Successfully established connection with API Server "192.168.63.161:6443"
[bootstrap] Detected server version: v1.8.0-alpha.0
[bootstrap] The server supports the Certificates API (certificates.k8s.io/v1beta1)
[csr] Created API client to obtain unique certificate for this node, generating keys and certificate signing request

**Comment by harshapic** [comment]
Got it working by approving "kubectl certificate approve"

**Comment by feiskyer** [comment]
@harshapic  Cool👍
