### ISSUE TITLE
Kubectl exec - Socket connection ERROR

### ISSUE THREAD

**Issue by harshapic** [kubernetes/frakti#176]
i have setup 1master 2 worker node setup using vmware_fusion (ubuntu xenial 64 vms). I followed all deployment steps given in documentation.

i am facing issue for kubectl exec to pod:

```
root@master-node:~# kubectl get nodes
NAME           STATUS    AGE       VERSION
master-node    Ready     35m       v1.6.5
worker1-node   Ready     33m       v1.6.5
worker2-node   Ready     31m       v1.6.5

root@master-node:~# kubectl exec -it my-nginx-1724589280-lshv0 /bin/bash
Error from server: error dialing backend: dial tcp 192.168.63.179:22521: getsockopt: connection refused
```

Any idea what i am doing wrong?
I am to ping worker-nodes and pod as well, but exec giving problem.

**Comment by resouer** [comment]
It looks like you are using cross host networking (which is not provided in k8s by default)? The easiest way is to follow: https://github.com/kubernetes/frakti/blob/master/docs/deploy.md#setting-up-the-worker-nodes

**Comment by harshapic** [comment]
I followed those steps and added "ip route add " on all 3 nodes.
My master node ip address: 192.168.63.168
worker1-node: 192.168.63.169
worker1-node: 192.168.63.170

ex on master node i added like this:

ip route add 10.244.2.0/24 via 192.168.63.169
ip route add 10.244.3.0/24 via 192.168.63.170

**Comment by feiskyer** [comment]
@harshapic Could you verify whether frakti is listening on IP `192.168.63.179`? It should serve on same IP as kubelet.

**Comment by harshapic** [comment]
Thanks feiskyer it helped....now i am able do kubelet exec ...changed /etc/hosts file to match ipaddress of frakti and kubelet...Now its working fine.
