### ISSUE TITLE
Running Vm images on Frakti?

### ISSUE THREAD

**Issue by harshapic** [kubernetes/frakti#179]
Is there is any way to run Vm images like(vmdk, qcow2, img etc) directly on frakti?
Just like rancher vm we can convert Vm images to container and then run as container using rancher vm? is something similar available On frakti?

As per my knowledge i can use qcow2 image directly on kvm if i choose kvm as my hypervisor. Then how can i run same qcow2 image on farkti as well if i choose "Frakti -> HyperD -> KVM".

**Comment by resouer** [comment]
Traditional disk image is not in scope of both k8s and frakti which are all container-centric.

But I'm curious about your use case. So, if you are asking for customized kernel, then BYOK (bring-your-own-kernel) to frakti seems to be a better answer, otherwise, it seems you can always package the file systems into a Docker image.

**Comment by harshapic** [comment]
Thanks for reply, ya i have scenario where my vm image is in qcow2 format and i need to run it on Kubernets -> Frakti -> hyperd -> KVM. That qcow2 image perfectly running on kvm which we tested it. So here is the the thing i know how to package my qcow2 img file system as container i did it already. I am not really getting BYOK part any examples how can i do it with frakti? Any references please.

**Comment by harshapic** [comment]
I just went through documentation again....Is this correct where we mention our own kernel?

echo -e "Kernel=/var/lib/hyper/kernel\n\
Initrd=/var/lib/hyper/hyper-initrd.img\n\

Do i need to mention my kernel here for HyperD as part of BYOK?

**Comment by feiskyer** [comment]
@harshapic Yep, the kernel `/var/lib/hyper/kernel` is built with config [here](https://github.com/hyperhq/hyperstart/blob/master/build/kernel_config), you could replace it with your own one.

**Comment by harshapic** [comment]
Awesome.. Got it...Another last this thing, Any other Kuberenets Annotations which frakti supports just like:
runtime.frakti.alpha.kubernetes.io/OSContainer : "True" (which uses docker instead hyperd).
 Any other annotations are there just for exploring?

**Comment by feiskyer** [comment]
> Any other Kuberenets Annotations which frakti supports just like: runtime.frakti.alpha.kubernetes.io/OSContainer : "True" (which uses docker instead hyperd).
@harshapic Only this one for switching to docker now.

**Comment by hwinkel** [comment]
@harshapic have you solved your use case to run a qcow or raw image on kubernetes? we have a similar use case to run a "stock" QCow VM Image. I would be fine trying to convert the format  it but can't really change the content.

**Comment by harshapic** [comment]
Yes bbva/kvm will help yo run smaller qcow images on kubernetes....via docker runtime..(will not work on hyperd)...tried to run ubuntu qcow2 image which is bigger image footprint didnt worked.

**Comment by harshapic** [comment]
@hwinkel above comment hope it helps u...let me know anything else looking out....

**Comment by hwinkel** [comment]
@harshapic thanks for that, we will give it a try with a given qcow workload.

**Comment by hwinkel** [comment]
I also still wondering how you select the BYOK Kernel images, will the kernel be part of the OCI Image, or separately provided?
