### ISSUE TITLE
Kubernetes Deployment - "privileged: true" Security Context - Runs on Docker instead Hypercontainer

### ISSUE THREAD

**Issue by harshapic** [kubernetes/frakti#187]
Below container i am using in my kubernetes deployment file: 
containers:
      - name: bbva
        image: bbvainnotech/kvm:latest
        imagePullPolicy: Always
        stdin: true
        tty: true
        env:
          - name: AUTO_ATTACH
            value: "yes"
        securityContext:
          privileged: true
If i use "privileged: true" i think its not running on Hypercontainer it automatically runs on "Docker" runtime.
I didn't used "OSContainer: "true" annotation in my kubernets file still it runs on docker!

**Comment by feiskyer** [comment]
@harshapic yep, privileged containers are running in docker instead of hypercontainer. This is expected behavior.

**Comment by feiskyer** [comment]
I'm closing this since this is the expected behavior.
