### ISSUE TITLE
Using relay bridge for better cni compatibility

### ISSUE THREAD

**Issue by YaoZengzeng** [kubernetes/frakti#191]
Steps:

0. Delete all the network configuration in the net ns

1. Setup one relay bridge in net ns and another one in host

2. Use one pair of veth device to connect the two relay bridge

3. Connect the "eth0" in netns to relay bridge in net ns

4. Configure the hyperContainer's network by cni result and the name of relay bridge in host

5. Connect the "tap0" device of hyperContainer to relay device in host

Now all works!

Data flow:
veth in host --> veth in ns (the original "eth0") --> relay bridge in ns --> veth for connection in ns
--> veth for connection in host --> relay bridge in host --> "tap0" of hyperContainer

**Comment by YaoZengzeng** [comment]
#192

**Comment by feiskyer** [comment]
Added in #192.
