### ISSUE TITLE
Evaluate and remove tmpfs workaround in favor of kubernetes/50596

### ISSUE THREAD

**Issue by resouer** [kubernetes/frakti#225]
See: https://github.com/kubernetes/kubernetes/pull/50596

Will evaluate and remove tmpfs workaround.

**Comment by resouer** [comment]
This does not work yet.

Filed https://github.com/kubernetes/kubernetes/pull/51927 to fix it. Let's see how it goes.

**Comment by adelton** [comment]
Shouldn't it be the flexVolume driver doing the cleanup if it added some data there? https://github.com/kubernetes/kubernetes/pull/51927#issuecomment-327544251 suggests that doing `RemoteAll` in the infrastructure code rather than in the individual driver code sounds dangerous.

**Comment by resouer** [comment]
Confirmed, this work with kubelet 1.7.5+
