### ISSUE TITLE
Update kubernetes vendors

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#231]
Kubelet CRI has added MountPropagation, we should update kubernetes vendors to include this change.

Refer to https://github.com/kubernetes/kubernetes/pull/46444.

**Comment by Crazykev** [comment]
@resouer I've already push libvirt patch to upstream, we don't need to use our branch anymore. Could you also update libvirt-go-xml vendor together with this?

**Comment by feiskyer** [comment]
@Crazykev cool.

**Comment by resouer** [comment]
@Crazykev The current k8s upstream is not steady, will fix this later.
