### ISSUE TITLE
Evaluate vendor manage tools

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#232]
We are using godep for managing vendors today, but it is not so easy to update standalone packages with godep. We should consider an alternative one. Some candidates include:

- [vndr](https://github.com/LK4D4/vndr): containerd and moby are using it.
- [glide](https://github.com/Masterminds/glide): helm and kompose are using it.
- [dep](https://github.com/golang/dep): dashboard is using it. But it's still not stable now, hoping to be the official toolchain in go 1.10.

I'd prefer vndr now, and we should switch to dep when it is stable.

**Comment by resouer** [comment]
Will do this first.
