### ISSUE TITLE
Releasing Frakti v1.1

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#241]
## TODOs

- [x] Bump version to v1.1 #242 
- [x] Release with v1.1 tag with release notes
- [x] Update changelog

## Draft release notes

Frakti v1.1 upgrades to kubernetes v1.8, enhances CNI network plugins and adds experimental unikernel support. It also includes various of enhancements and bug fixes.

## Features and Updates

- #192 Improves CNI plugin compatibility
- #196 #208 Adds general support for CNI plugins, e.g. flannel and calico plugin
- #219 #223 #226 Adds experimental support for unikernel
- #217 Fixes problem of weave plugin
- #199 #207 Adds cinder flexvolume plugin
- #188 Fixes CNI podName problem
- #189 Fixes CNI cleanup when sandbox runs failure
- #205 Increases memory limits for kube-dns
- #211 #212 #221 #224 #230 Adds unit tests for various packages

## External Dependency Version Information

- Kubernetes v1.8
- Hyperd v1.0
- Docker v1.12-v17.03

**Comment by resouer** [comment]
All done, will close it. 🥇
