### ISSUE TITLE
Consider support for Windows Hyper-V

### ISSUE THREAD

**Issue by AceHack** [kubernetes/frakti#273]
please support windows hyper-v hypervisor

**Comment by resouer** [comment]
@AceHack Thanks for bring this up! While may I ask are you suggesting the Hyper-V VM or [Hyper-V container](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container)?

frakti focus on "container" management in Kubernetes, so the later would make more sense.

**Comment by AceHack** [comment]
Yeah, Hyper-V containers sounds great, what I really want is unikernals in hyper-v via frakti.  This issue working in Hyper-V would be awesome.
https://github.com/kubernetes/frakti/issues/99

**Comment by resouer** [comment]
@AceHack  The use case would be running docker image with Hyper-V containers just like what you can do with runV/Hyper. Not sure if it's your expectation?

**Comment by AceHack** [comment]
@resouer Yes, I'm hoping not to have to create specific containers per hypervisor, one container to work on any hypervisor.
