### ISSUE TITLE
Upgrade cri to v1alpha2

### ISSUE THREAD

**Issue by liyanyanli** [kubernetes/frakti#297]
**cri-tool version: master branch**
`[root@frakti1 crictl]# ./crictl ps
DEBU[0000] ListContainerRequest: &ListContainersRequest{Filter:&ContainerFilter{Id:,State:&ContainerStateValue{State:CONTAINER_RUNNING,},PodSandboxId:,LabelSelector:map[string]string{},},} 
DEBU[0000] ListContainerResponse: nil                   
FATA[0000] listing containers failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService `

I think, it is necessary to upgrade v1alpha1 to v1alpha2！

**Comment by resouer** [comment]
Please note that v1alpha2 is for 1.10, which has not been released. See https://github.com/kubernetes/frakti/issues/279, will close this one.

Please use crictl version v1.0.0-alpha.0  with frakti 1.9.x.
