### ISSUE TITLE
kubelet node register has failed

### ISSUE THREAD

**Issue by diffsz** [kubernetes/frakti#304]
we want to try the k8s+frakti+hyperd program recently, after I deploy according to wiki on the steps, start kubelet node found node has not been successfully registered, node status is always NOTREADY, check the frakti’s log found imagefsinfo wrong, see the frakti code found this func is returned nil, do not know if this is not the cause of the problem? Or do I need another configuration? Thanks

frakti log：
E0306 14:40:47.577493   25964 remote_image.go:146] ImageFsInfo from image service failed: rpc error: code = Unknown desc = not implemented
E0306 14:40:47.577516   25964 kubelet.go:1234] Image garbage collection failed once. Stats initialization may not have completed yet: rpc error:
I0306 14:40:47.579173   25964 certificate_manager.go:361] Requesting new certificate.
I0306 14:40:47.579345   25964 server.go:296] Adding debug handlers to kubelet server.

**Comment by resouer** [comment]
ImageFS API is not supported in frakti for now, it's expected. But this is not a blocker for you node failure.

As it is the node that is not ready, please post the logs of kubelet instead of frakti.

**Comment by diffsz** [comment]
sorry, i get mistake, that log is kubelet‘log

**Comment by resouer** [comment]
@diffsz  Thanks, but they are not related to kubelet down, could you please post more kubelet log here? Especially the start and stop part.

**Comment by resouer** [comment]
close as inactive, please feel free to re-open it when you come back.
