### ISSUE TITLE
Network in POD doesn't work fine

### ISSUE THREAD

**Issue by gavinmy15** [kubernetes/frakti#311]
I follow this [document](https://github.com/kubernetes/frakti/blob/master/docs/deploy.md) to establish a one-node k8s cluster with flannel network, hyperd at commit [d493b1bf1f9d21277203d18f08928fd56a3a73af](https://github.com/hyperhq/hyperd/commit/d493b1bf1f9d21277203d18f08928fd56a3a73af) (to avoid using Interface.Mtu because of other issue) and frakti 1.9.1 release.

POD can be created but there is a problem with networking.
I execute bash in the POD, and try to ping other POD's IPs then I fail.

I find a workaround that ping the POD IP from master node, the networking of that POD will recover,
but the WA is weird, do I miss some configurations?
Thanks

**Comment by resouer** [comment]
Which frakti release?

**Comment by gavinmy15** [comment]
[Frakti github 1.9.1 release](https://github.com/kubernetes/frakti/releases)
[Frakti v1.9.1](https://github.com/kubernetes/frakti/archive/1.9.1.tar.gz)

**Comment by resouer** [comment]
@gavinmy15  Sorry, I can't re-produce this issue and it's very weird, I can not tell why you ping master and things recover ...

Can you please deploy a new cluster in new machines?

**Comment by gavinmy15** [comment]
@resouer 
New cluster works fine, I cannot re-produce the environment too.

**Comment by fanux** [comment]
Can frakti work with calico network?

**Comment by resouer** [comment]
@fanux Yes, it works with any bridged CNI plugin

**Comment by gavinmy15** [comment]
It's fine to close because I cannot reproduce the issue again.
