### ISSUE TITLE
Upgrade dockershim to 1.10

### ISSUE THREAD

**Issue by resouer** [kubernetes/frakti#316]
Update the dockershim to 1.10

Release check: https://github.com/kubernetes/kubernetes/releases

**Comment by liyanyanli** [comment]
I will do it.

**Comment by resouer** [comment]
Please attention to CRI change: https://github.com/kubernetes/frakti/issues/279

**Comment by resouer** [comment]
@liyanyanli If you will do this. You can start now, please update the vendor to v1.10.0-rc.1

And later, when 1.10.0 stable is out, update vendor to it.

**Comment by liyanyanli** [comment]
Ok, I see. thank you very much！

**Comment by liyanyanli** [comment]
Should we implement dockershim inside frakti and not rely on dockeshim of Kubernetes?

Kubernetes PR: [dockershim: remove the use of kubelet's internal API](https://github.com/kubernetes/kubernetes/commit/e8da890aee15e36f089d64098fd25b88266a52b3#diff-99802aef301353226cc4233749846c68)

**Comment by resouer** [comment]
@liyanyanli dockershim is a workaround, we can keep it for now. In next or next next release, we will not use dockershim and cooperate with containerd instead. You can help with that part if you are interested.

See: https://github.com/cncf/soc#katacontainers-support-for-containerdcri-containerd

**Comment by resouer** [comment]
@liyanyanli [1.10.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.10.0) is out now. Please update the vendor to this stable release if possible.

If you have already finish the work, please just send out and we can update it to 1.10.0 stable later.

**Comment by liyanyanli** [comment]
I have updated the vendor to 1.10.0. However, the changes made by [dockershim](https://github.com/kubernetes/kubernetes/commit/e8da890aee15e36f089d64098fd25b88266a52b3#diff-16c44fd3516b9794e49c760f0af2d777L104) make frakti have the following problems when compiling and I am trying to solve it.

example:
```
./frakti.go:113:41: cannot use privilegedRuntime (type *docker.PrivilegedRuntime) as type "k8s.io/frakti/pkg/runtime".RuntimeService in argument to manager.NewFraktiManager:
        *docker.PrivilegedRuntime does not implement "k8s.io/frakti/pkg/runtime".RuntimeService (wrong type for Attach method)
                have Attach(context.Context, *v1alpha2.AttachRequest) (*v1alpha2.AttachResponse, error)
                want Attach(*v1alpha2.AttachRequest) (*v1alpha2.AttachResponse, error)
```
I have two solutions:

1.  Implement dockershim inside frakti 

2. Frakti starts dockershim server inside, then connects dockershim's grpc interface

What do you think? Thanks very much！

**Comment by resouer** [comment]
@liyanyanli Please choose 2. 

Just make frakti work like a CRI proxy. Thank you very much!
