### ISSUE TITLE
[GSoC] Which Category to choose for this GSoC project

### ISSUE THREAD

**Issue by urvil38** [kubernetes/frakti#321]
which category is applied for this project?There is no category regarding to **containerd**.Should I applied for **kubernetes** or **security**?

**Comment by urvil38** [comment]
which category is applied for this project?There is no category regarding to **containerd**.Should I applied for **kubernetes** or **security**?

**Comment by resouer** [comment]
Choose kubernetes please, there's nothing related to security.
