### ISSUE TITLE
Upgrade frakti to Kubernetes v1.12

### ISSUE THREAD

**Issue by resouer** [kubernetes/frakti#344]
The Kubernetes v1.12 release is on-the-fly.

@liyanyanli Would you be able to help?

**Comment by resouer** [comment]
ping @liyanyanli , any progress or update here?

**Comment by liyanyanli** [comment]
I am very sorry, the progress is a bit slow, I am trying my best to update vendor.

**Comment by resouer** [comment]
Already done!
