### ISSUE TITLE
Consider filter out unnecessary pods in ListPodSandbox  

### ISSUE THREAD

**Issue by resouer** [kubernetes/frakti#43]
For now we will list all pods (containers) managed by hyperd, thus user created pod will also be parsed by frakti and report `failed to parse container name`. 

We need to consider add a filter to it. (e.g. special prefix?)

**Comment by feiskyer** [comment]
This is actually a bug in ListPodSandbox and ListContainer, should continue the loop instead of reporting a error. Will file a fix later.
