### ISSUE TITLE
Kubectl exec: connection refused

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#53]
When enabled frakti with kubelet, `kubectl exec` failed with errors:

```
cluster/kubectl.sh exec busybox-983667326-wlbt7 ip addr
Error from server: error dialing backend: dial tcp 172.16.1.134:22521: getsockopt: connection refused
```

**Comment by resouer** [comment]
Is this happens on latest hyperd master?

**Comment by feiskyer** [comment]
It seems the bug of frakti, it doesn't listen to 172.16.1.134:22521 while exec is executing.
