### ISSUE TITLE
Support CNI network plugin in Frakti

### ISSUE THREAD

**Issue by resouer** [kubernetes/frakti#58]
Need to support CNI plugin in Kubernetes +  Frakti. The implementation requires finding a way to generate network configuration from CNI and pass these information to hyperd in expected syntax.

A very similar approach is CNI plugin support in CRI-O, please check these for details: 

https://github.com/kubernetes-incubator/cri-o/pull/237
https://github.com/kubernetes-incubator/cri-o#setup-cni-networking

TODOs:

- [x] Basic cni network plugin support #62 
- [x] Checkpointing network info
- [x] CNI configure examples
- [x] CNI e2e tests
- [ ] ~~deployment, e.g. by `make install`~~

**Comment by resouer** [comment]
assign to @Monster-Z who volunteered to fix this

**Comment by feiskyer** [comment]
@YaoZengzeng Would you like to continue those CNI related work?

**Comment by YaoZengzeng** [comment]
@feiskyer Yes, of course

**Comment by feiskyer** [comment]
TIP: we could avoid network interface scanning after https://github.com/containernetworking/cni/pull/145 is merged.

**Comment by feiskyer** [comment]
All done.

**Comment by resouer** [comment]
@YaoZengzeng https://github.com/containernetworking/cni/pull/145 is merged, please update the existing code when you have time.
