### ISSUE TITLE
Container Runtime Interface integration with Hyper

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#8]
This document tracks the process of the container runtime interface integration with Hyper.
## Frakti core features
- [x] Manage pods/containers/images according to kubelet [new runtime API](https://github.com/kubernetes/kubernetes/tree/master/docs/proposals/runtime-client-server.md)
  - pod sandboxes
    - [x] create pod sandbox
    - [x] list pod sandbox
    - [x] delete pod sandbox #11 
    - [x] get pod sandbox’s status
  - containers
    - [x] create container
    - [x] start container
    - [x] stop container
    - [x] delete container
    - [x] list containers
    - [x] get container status
    - [x] exec in container
    - [x] port forwarding
    - [x] container logging
  - images
    - [x] list images
    - [x] pull image
    - [x] delete image
    - [x] get image status
- [ ] Hack scripts for easily setup a local enviroment
  - [x] hack/local-up-cluster.sh
  - [ ] Vagrant or minikube
- [x] testing
  - [x] Unit tests
  - [x] End-to-end tests
  - [x] Kubernetes node e2e tests
- [x] Cluster deployment
  - [x] Cluster deploy frakti for kubernetes clusters
- [x] Documentation
  - [x] Admin and user guide
  - [x] Frakti specific features which are different from Docker

## Requirements for Hyper
- [x] Container-level APIs: StartContainer/StopContainer https://github.com/hyperhq/hyperd/pull/445

## References
- [Container runtime interface planning](https://github.com/kubernetes/kubernetes/issues/28789)
- [Network plugin for client/server container runtimes](https://github.com/kubernetes/kubernetes/issues/28667)
- [Client/server container runtime proposal](https://github.com/kubernetes/kubernetes/tree/master/docs/proposals/runtime-client-server.md)

**Comment by danehans** [comment]
Why doesn't hyper support OCI through the [cri-o](https://github.com/kubernetes-incubator/cri-o) project?

**Comment by resouer** [comment]
@danehans Yes, HyperContainer has a OCI runtime named [RunV](https://github.com/hyperhq/runv)
RunV support in cri-o has been proposed here: https://github.com/kubernetes-incubator/cri-o/issues/168

But cri-o+runv is far from being useable, while `hyper.sh` requires a solution that works at least, we need to rely on `frakti` for at least a period of time. Tricky refactoring is needed on both RunV and cri-o sides, we are very appreciated if you are willing to collaborate :)

And we have also informed node team that we will consider merge `frakit` to cri-o if we achieved runv integration (which I think it's hopeful).

**Comment by feiskyer** [comment]
I'm closing this issue since frakti v0.1 has been released for a few days.
