### ISSUE TITLE
/var/lib/frakti/sandbox does not automatically create

### ISSUE THREAD

**Issue by resouer** [kubernetes/frakti#86]
In fresh new environment:
```
E0314 02:26:12.316677   11713 hyper_checkpoint.go:119] Failed to list checkpoint store: open /var/lib/frakti/sandbox: no such file or directory
```

@YaoZengzeng Is this directory expected to automatically created?

**Comment by heartlock** [comment]
/var/lib/frakti/sandbox will not be created until you create a sandbox. I will fix it. @resouer
